export const assetsData = [
  { 
    id: 'AST-1001', 
    assetCode: 'TGBS/B/L10',
    name: 'MacBook Pro 16"', 
    category: 'Laptop', 
    serial: 'C02YK1234', 
    processor: 'Apple M2 Pro (12-core)',
    ram: '32 GB',
    storage: '512 GB SSD',
    monitorName: 'Built-in Retina Display',
    monitorSerial: 'RET-16-9921',
    mouseModel: 'Apple Magic Mouse 2',
    mouseSerial: 'MS-APP-8821',
    keyboardSerial: 'KB-BUILTIN-01',
    os: 'macOS Sonoma 14.2',
    software: 'MS Office 365, Xcode, VS Code, Slack',
    simNumber: '',
    simPhoneNumber: '',
    simCarrier: '',
    simPlanDetails: '',
    status: 'Assigned', 
    assignedTo: 'Sarah Jenkins',
    assignedToEmail: 'sarah.j@company.com',
    location: 'New York HQ',
    purchaseDate: '2022-05-10',
    modelDate: 'Mar-18'
  },
  { 
    id: 'AST-1002', 
    name: 'Dell OptiPlex 7090 Desktop Workstation', 
    category: 'Desktop', 
    serial: 'CPU-DEL-7090-X1', 
    processor: 'Intel Core i7-12700',
    ram: '16 GB DDR4',
    storage: '1 TB NVMe SSD + 1 TB HDD',
    monitorName: 'Dell UltraSharp 27" 4K',
    monitorSerial: 'MON-DEL-2722-A',
    mouseModel: 'Logitech MX Master 3S',
    mouseSerial: 'MS-LOG-MX3-01',
    keyboardSerial: 'KB-LOG-K120-01',
    os: 'Windows 11 Pro',
    software: 'MS Office 365, AutoCAD 2024, CrowdStrike Antivirus',
    simNumber: '',
    simPhoneNumber: '',
    simCarrier: '',
    simPlanDetails: '',
    status: 'Assigned', 
    assignedTo: 'Michael Chang',
    assignedToEmail: 'michael.c@company.com',
    location: 'London Office',
    purchaseDate: '2023-01-15'
  },
  { 
    id: 'AST-1003', 
    name: 'HP ProDesk 600 G6 Desktop', 
    category: 'Desktop', 
    serial: 'CPU-HP-600G6-99', 
    processor: 'Intel Core i5-11500',
    ram: '16 GB',
    storage: '512 GB NVMe SSD',
    monitorName: 'HP EliteDisplay E243 24"',
    monitorSerial: 'MON-HP-24FH-02',
    mouseModel: 'HP Optical USB Mouse',
    mouseSerial: 'MS-HP-USB-55',
    keyboardSerial: 'KB-HP-USB-55',
    os: 'Windows 10 Pro',
    software: 'MS Office 365, Acrobat Reader, Chrome',
    simNumber: '',
    simPhoneNumber: '',
    simCarrier: '',
    simPlanDetails: '',
    status: 'Available', 
    assignedTo: '',
    assignedToEmail: '',
    location: 'New York HQ',
    purchaseDate: '2023-04-10'
  },
  { 
    id: 'AST-1004', 
    name: 'Lenovo ThinkPad X1 Carbon Gen 10', 
    category: 'Laptop', 
    serial: 'PF123456', 
    processor: 'Intel Core i7-1260P',
    ram: '32 GB LPDDR5',
    storage: '1 TB SSD',
    monitorName: 'Built-in 14" WUXGA',
    monitorSerial: 'MON-LNV-14-X1',
    mouseModel: 'Logitech Pebble M350',
    mouseSerial: 'MS-LOG-PB-44',
    keyboardSerial: 'KB-BUILTIN-X1',
    os: 'Windows 11 Pro',
    software: 'MS Office 365, Figma, Docker Desktop, Zoom',
    simNumber: '8991101234567890123F',
    simPhoneNumber: '+1 (555) 432-1098',
    simCarrier: 'Verizon Wireless',
    simPlanDetails: '5G LTE Corporate Unlimited',
    status: 'Assigned', 
    assignedTo: 'David Smith',
    assignedToEmail: 'david.s@company.com',
    location: 'Remote',
    purchaseDate: '2023-03-05'
  },
  { 
    id: 'AST-1005', 
    name: 'Apple iPhone 13 Pro (128GB)', 
    category: 'Mobile', 
    serial: 'FFGH892K', 
    processor: 'A15 Bionic',
    ram: '6 GB',
    storage: '128 GB NVMe',
    monitorName: '',
    monitorSerial: '',
    mouseModel: '',
    mouseSerial: '',
    keyboardSerial: '',
    os: 'iOS 17.2',
    software: 'Microsoft Outlook, Slack, Teams, MDM Agent',
    simNumber: '8991410987654321098F',
    simPhoneNumber: '+1 (555) 789-0123',
    simCarrier: 'AT&T Mobility',
    simPlanDetails: 'Corporate Executive 5G Data & Voice',
    status: 'Assigned', 
    assignedTo: 'Emily Davis',
    assignedToEmail: 'emily.d@company.com',
    location: 'San Francisco',
    purchaseDate: '2022-08-12'
  },
  { 
    id: 'AST-1006', 
    name: 'Corporate 5G Wi-Fi SIM Card', 
    category: 'SIM Card', 
    serial: '8991223344556677889F', 
    processor: '',
    ram: '',
    storage: '',
    monitorName: '',
    monitorSerial: '',
    mouseModel: '',
    mouseSerial: '',
    keyboardSerial: '',
    os: '',
    software: 'Roaming Enabled',
    simNumber: '8991223344556677889F',
    simPhoneNumber: '+1 (555) 321-7654',
    simCarrier: 'T-Mobile Enterprise',
    simPlanDetails: '100GB High-Speed International Data',
    status: 'Available', 
    assignedTo: '',
    assignedToEmail: '',
    location: 'New York HQ',
    purchaseDate: '2023-09-15'
  },
  { 
    id: 'AST-1007', 
    name: 'Dell PowerEdge R740 Server', 
    category: 'Server', 
    serial: '2J4K5M1', 
    processor: '2x Intel Xeon Silver 4214',
    ram: '128 GB ECC DDR4',
    storage: '4x 2 TB SAS HDD (RAID 10)',
    monitorName: 'Rack Console KVM',
    monitorSerial: 'KVM-RACK-01',
    mouseModel: 'Integrated KVM Mouse',
    mouseSerial: 'KVM-MS-01',
    keyboardSerial: 'KVM-KB-01',
    os: 'Ubuntu Server 22.04 LTS',
    software: 'Docker Enterprise, PostgreSQL 15, Nginx, Prometheus',
    simNumber: '',
    simPhoneNumber: '',
    simCarrier: '',
    simPlanDetails: '',
    status: 'Available', 
    assignedTo: '',
    assignedToEmail: '',
    location: 'Data Center 1',
    purchaseDate: '2020-09-30'
  },
];

export const employeesData = [
  { id: 'EMP-001', name: 'Sarah Jenkins', role: 'Software Engineer', department: 'Engineering', email: 'sarah.j@company.com', phone: '+1 (555) 123-4567', assetsCount: 2 },
  { id: 'EMP-002', name: 'Michael Chang', role: 'Product Manager', department: 'Product', email: 'michael.c@company.com', phone: '+1 (555) 234-5678', assetsCount: 1 },
  { id: 'EMP-003', name: 'David Smith', role: 'UX Designer', department: 'Design', email: 'david.s@company.com', phone: '+1 (555) 345-6789', assetsCount: 3 },
  { id: 'EMP-004', name: 'Emily Davis', role: 'HR Director', department: 'Human Resources', email: 'emily.d@company.com', phone: '+1 (555) 456-7890', assetsCount: 1 },
  { id: 'EMP-005', name: 'James Wilson', role: 'Sales Lead', department: 'Sales', email: 'james.w@company.com', phone: '+1 (555) 567-8901', assetsCount: 2 },
];

export const vendorsData = [
  { id: 'VND-001', name: 'Dell Technologies', type: 'Hardware Supplier', contact: 'Alex Rivera', email: 'alex@dell-partners.com', phone: '+1 (800) 123-4567', activePOs: 3, status: 'Active' },
  { id: 'VND-002', name: 'Apple Enterprise', type: 'Hardware Supplier', contact: 'Sam Chen', email: 'sam.c@apple-ent.com', phone: '+1 (800) 234-5678', activePOs: 1, status: 'Active' },
  { id: 'VND-003', name: 'Cisco Systems', type: 'Network Equipment', contact: 'Jordan Lee', email: 'jlee@cisco.com', phone: '+1 (800) 345-6789', activePOs: 0, status: 'Active' },
  { id: 'VND-004', name: 'Microsoft AppSource', type: 'Software Provider', contact: 'Casey Smith', email: 'casey@microsoft.com', phone: '+1 (800) 456-7890', activePOs: 5, status: 'Active' },
];

export const maintenanceTasksData = [
  { id: 'MNT-201', asset: 'Cisco Meraki MR46', issue: 'Firmware Update', assignedTo: 'John Doe', priority: 'High', status: 'In Progress', dueDate: '2023-11-01' },
  { id: 'MNT-202', asset: 'MacBook Pro 16"', issue: 'Battery Replacement', assignedTo: 'Jane Smith', priority: 'Medium', status: 'Scheduled', dueDate: '2023-11-05' },
  { id: 'MNT-203', asset: 'Dell PowerEdge R740', issue: 'Annual Service', assignedTo: 'System Admin Team', priority: 'Low', status: 'Pending Approval', dueDate: '2023-11-15' },
  { id: 'MNT-204', asset: 'Lenovo ThinkPad X1', issue: 'Screen Repair', assignedTo: 'John Doe', priority: 'High', status: 'Completed', dueDate: '2023-10-25' },
];
